library(tidyverse)
rna_class <- read.csv("~/Downloads/rna_class2.csv", sep = "\t")
colnames(rna_class) <- c("mrna", "class")
rna <- read.csv("~/Downloads/rna_list.txt", sep="\t")
colnames(rna) <- c("mrna", "rna_class")
snorna_all <- read.csv("~/Downloads/snoRNA_log2fc.csv") %>% rename_at("RNA", ~"mrna") %>% mutate(rna_class="snoRNA")

csl4ph_pBM5 <- read.csv("~/Downloads/files/WT_pBM5vscsl4ph_pBM5.tsv", sep = "\t") %>% filter(logFC > 1.0 & PValue < 0.01) 
df <- merge(csl4ph_pBM5, rna, by="mrna", all = F) %>% select(mrna, rna_class)
snorna <- snorna_all %>% filter(WT_pBM5vscsl4ph_pBM5 > 4.0) %>% select(mrna, rna_class) 
df1 <- rbind(df, snorna) %>% group_by(rna_class) %>% tally()
colnames(df1) <- c("RNA_Class", "csl4ph_pBM5")

enp1_1_pBM5 <- read.csv("~/Downloads/files/WT_pBM5vsenp1_1_pBM5.tsv", sep = "\t") %>% filter(logFC > 1.0 & PValue < 0.01) 
df <- merge(enp1_1_pBM5, rna, by="mrna", all = F) %>% select(mrna, rna_class)
snorna <- snorna_all %>% filter(WT_pBM5vsenp1_1_pBM5 > 4.0) %>% select(mrna, rna_class) 
df2 <- rbind(df, snorna) %>% group_by(rna_class) %>% tally()
colnames(df2) <- c("RNA_Class", "enp1_1_pBM5")

WT_pBM766 <- read.csv("~/Downloads/files/WT_pBM5vsWT_pBM766.tsv", sep = "\t") %>% filter(logFC > 1.0 & PValue < 0.01) 
df <- merge(WT_pBM766, rna, by="mrna", all = F) %>% select(mrna, rna_class)
snorna <- snorna_all %>% filter(WT_pBM5vsWT_pBM766 > 4.0) %>% select(mrna, rna_class) 
df3 <- rbind(df, snorna) %>% group_by(rna_class) %>% tally()
colnames(df3) <- c("RNA_Class", "WT_pBM766")

csl4ph_pBM766 <- read.csv("~/Downloads/files/WT_pBM5vscsl4ph_pBM766.tsv", sep = "\t") %>% filter(logFC > 1.0 & PValue < 0.01) 
df <- merge(csl4ph_pBM766, rna, by="mrna", all = F) %>% select(mrna, rna_class)
snorna <- snorna_all %>% filter(WT_pBM5vscsl4ph_pBM766 > 4.0) %>% select(mrna, rna_class)
df4 <- rbind(df, snorna) %>% group_by(rna_class) %>% tally()
colnames(df4) <- c("RNA_Class", "csl4ph_pBM766")

enp1_1_pBM766 <- read.csv("~/Downloads/files/WT_pBM5vsenp1_1_pBM766.tsv", sep = "\t") %>% filter(logFC > 1.0 & PValue < 0.01) 
df <- merge(enp1_1_pBM766, rna, by="mrna", all = F) %>% select(mrna, rna_class)
snorna <- snorna_all %>% filter(WT_pBM5vsenp1_1_pBM766 > 4.0) %>% select(mrna, rna_class)
df5 <- rbind(df, snorna) %>% group_by(rna_class) %>% tally()
colnames(df5) <- c("RNA_Class", "enp1_1_pBM766")

temp <- merge(df1, df2, by="RNA_Class", all = TRUE)
temp <- merge(temp, df3, by="RNA_Class", all = TRUE)
temp <- merge(temp, df4, by="RNA_Class", all = TRUE)
temp <- merge(temp, df5, by="RNA_Class", all = TRUE)

write.csv(temp, file = "~/Desktop/rna_class_logfc4.csv")

df1 <- merge(csl4ph_pBM5, rna_class, by="mrna") %>% select(mrna, class) %>% group_by(class) %>% tally()
df2 <- merge(enp1_1_pBM5, rna_class, by="mrna") %>% select(mrna, class) %>% group_by(class) %>% tally()
#df3 <- merge(WT_pBM766, rna_class, by="mrna") %>% select(mrna, class) %>% group_by(class) %>% tally()
df4 <- merge(csl4ph_pBM766, rna_class, by="mrna") %>% select(mrna, class) %>% group_by(class) %>% tally()
df5 <- merge(enp1_1_pBM766, rna_class, by="mrna") %>% select(mrna, class) %>% group_by(class) %>% tally()
df6 <- rna_class %>% group_by(class) %>% tally()
df <- cbind(df1,df2[,2],df4[,2],df5[,2], df6[,2])
colnames(df) <- c("Class", "csl4ph_pBM5", "enp1_1_pBM5", "csl4ph_pBM766", "enp1_1_pBM766", "Total numbers")
write.csv(df, file = "~/Desktop/mrna_class_logfc_1.csv")
