library(dplyr)
library(tidyverse)
library(data.table)
library(ggplot2)
setwd("~/Desktop/Paul_et_al_2019/")
rpkm <- read.csv("./results/wt_rpkm.csv", sep = "\t")[c(1,6)]
df <- read.csv("./results/log2FC_all_rb.tsv", sep="\t")
colnames(df) <- c("gene", "rrp6", "dis3", "csl4", "enp1", "srm1")
df3 <- read.csv("./annotation/tollarvy_rna_classes2.csv", sep="\t")
levels(df3$Class)[levels(df3$Class) %in% c("I", "II", "III")] <- "I-III"
levels(df3$Class)[levels(df3$Class) %in% c("IV", "V", "VI", "VII", "VIII")] <- "IV-VIII"
levels(df3$Class)[levels(df3$Class) %in% c("IX", "X")] <- "IX-X"
df <- df[complete.cases(df),]
df4 <- merge(df,df3, by="gene", all=F)
df5 <- merge(df4, rpkm, by = "gene", all=F)
png("./Figures/figure2B.1.png")
ggplot(df5, aes(log(rpkm), rrp6, color=Class)) + geom_point(size=0.3) + theme_bw() + xlim(-5,10) + ylim(-5,5)
dev.off()
png("./Figures/figure2B.2.png")
ggplot(df5, aes(log(rpkm), dis3, color=Class)) + geom_point(size=0.3) + theme_bw()+ xlim(-5,10) + ylim(-5,5)
dev.off()
png("./Figures/figure2B.3.png")
ggplot(df5, aes(log(rpkm), csl4, color=Class)) + geom_point(size=0.3) + theme_bw()+ xlim(-5,10) + ylim(-5,5)
dev.off()
png("./Figures/figure2B.4.png")
ggplot(df5, aes(log(rpkm), enp1, color=Class)) + geom_point(size=0.3) + theme_bw()+ xlim(-5,10) + ylim(-5,5)
dev.off()
png("./Figures/figure2B.5.png")
ggplot(df5, aes(log(rpkm), srm1, color=Class)) + geom_point(size=0.3) + theme_bw()+ xlim(-5,10) + ylim(-5,5)
dev.off()
